name: llllm-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - rasterio
  - pip:
    - langchain
    - langchain-ollama
    - langchain-community
    - duckduckgo-search
    - mercantile
    - geopy
    - ipywidgets
    - jupyterlab
    - planetary-computer
    - pystac-client
    - streamlit
    - streamlit-folium
    - watchdog
    - altair
    - osmnx
