name: llllm-env
channels:
  - conda-forge
dependencies:
  - python=3
  - pip
  - pip:
    - openai
    - langchain
    - duckduckgo-search
    - mercantile
    - geopy
    - ipywidgets
    - jupyterlab
