name: llllm-env
channels:
  - conda-forge
dependencies:
  - python=3
  - pip
  - osmnx=1.3.1
  - pip:
    - openai==0.27.8
    - langchain==0.0.215
    - duckduckgo-search==3.8.3
    - mercantile==1.2.1
    - geopy==2.3.0
    - ipywidgets==8.0.6
    - jupyterlab==4.0.2
    - planetary-computer==0.5.1
    - pystac-client==0.7.2
    - streamlit==1.24.1
    - streamlit-folium==0.12.0
    - watchdog==3.0.0
    - aim==3.17.5
