apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llllm-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - "{{ .Values.streamlit.host }}"
    secretName: llllm-tls
  rules:
  - host: "{{ .Values.streamlit.host }}"
    http:
      paths:
      - backend:
          service:
            name: llllm-streamlit-app-service
            port:
              number: 8501
        path: /
        pathType: Prefix
