name: Deploy Terraform Infrastructure to GCP
on:
  workflow_dispatch: # allows for manual invocation
  push:
    branches:
      - main
      - feat/deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: Configure kubectl
      run: |
        gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }}
    - name: Create contacts configmap
      run: kubectl apply -f deployment/k8s/configmap.yaml --namespace project-llllm
    - name: 'Set up Helm'
      uses: 'Azure/setup-helm@v1'
    - name: "Deploy Helm Chart"
      run: |
        helm upgrade --install project-llllm deployment/helm --create-namespace --namespace project-llllm --set secrets.openai_api_key=${{ secrets.OPENAI_API_KEY }}
